### ISSUE TITLE
Rework tabs according to WAI reco

### ISSUE THREAD

**Issue by ET-AD** [adeo/mozaic-design-system#1028]
# 🚀 Pattern enhancement proposal

### What kind of enhancement are you proposing ?
	
- [ ] On sketch file
- [x] On Documentation
- [x] On source code

### Description

- remove `role="presentation"` from tabs
- tab must be a button tag
- convert `ul` to `div`
- remove li tag (button must be direct children

### Justification
page reload => navigation menu => link list
no reload => tablist => WAI reco https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html

**Comment by tiloyi** [comment]
Related link: https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel
