### ISSUE TITLE
Accordion: a11y enhancement

### ISSUE THREAD

**Issue by Marine-Fabien** [adeo/mozaic-design-system#1037]
# 🚀 Pattern enhancement proposal

### What kind of enhancement are you proposing ?
	
- [ ] On sketch file
- [x] On Documentation
- [x] On source code

### Description
Delete the background image inside accordion button.
<img width="658" alt="Capture d’écran 2022-02-21 à 16 22 48" src="https://user-images.githubusercontent.com/77010633/154984040-e3bd3817-a5ee-4fa5-a287-93ad28ea596a.png">

### Justification
In order to comply with accessibility guidelines, you should avoid using a background image in css. 
In the case of the accordion, we have a colour contrast problem with the use of a css background image. 

**Anything else relevant?**
To fix it, I propose to change this html structure to put the svg inside the button tag

<img width="1299" alt="Capture d’écran 2022-02-21 à 16 05 30" src="https://user-images.githubusercontent.com/77010633/154983528-c637cf85-5394-4d1d-b082-21396da0a68e.png">

**Comment by tiloyi** [comment]
@all-contributors please add @matthieu-castier  for code
