### ISSUE TITLE
Create multi selection

### ISSUE THREAD

**Issue by AlexFe96** [adeo/mozaic-design-system#1039]
Hi there! 😄

In our application we need to display a multi selection. Can you add it, please and then you have created this component i am going to create it for react-mozaic part.

# 🚀 Pattern addition proposal
https://www.figma.com/file/M5vv4mAAUIsFe9l6j6zSdG/PPM?node-id=2479%3A61420

### Description
 A clear and concise description of why this pattern is needed.

**Anything else relevant?**

**Comment by tiloyi** [comment]
Hi @AlexFe96 ,
The component you need is being created in Mozaic-Vue. You can see more here => https://github.com/adeo/mozaic-vue/discussions/557

Which framework do you use?

**Comment by AlexFe96** [comment]
Hi @tiloyi I use React.

**Comment by AlexFe96** [comment]
so i think first of all we have created a component in mozaic design system and next step it is going to carry to library realization like Vue, React and etc

**Comment by tiloyi** [comment]
Released in **v1.29.0** of the Design System, with the addition of components **Autocomplete**, **Dropdown** & **Listbox**
=> https://github.com/adeo/mozaic-design-system/releases/tag/v1.29.0

Issues have been created in **Mozaic-React** to add these components to the React version of the Design System.

I invite you to follow the progress via these links:
- https://github.com/adeo/mozaic-react/issues/66
- https://github.com/adeo/mozaic-react/issues/67
- https://github.com/adeo/mozaic-react/issues/68
