### ISSUE TITLE
Add the spinner icon

### ISSUE THREAD

**Issue by AlexFe96** [adeo/mozaic-design-system#1052]
# 🚀 Styleguide feature request
https://www.figma.com/file/M5vv4mAAUIsFe9l6j6zSdG/PPM?node-id=2500%3A58283

### Description
We don't have spin icon which we can indicate loading state

### Describe the solution you'd like
Add spin icon into mozaic icon

### Describe alternatives you've considered

**Comment by tiloyi** [comment]
Hi @AlexFe96 ,
Thank you for your message.
This component is coming in the delivery next week (Wednesday 23rd March 2022).

I'll keep you posted as soon as it's released :)

**Comment by AlexFe96** [comment]
Hi @tiloyi, thank you, i'll be looking forward to it.

**Comment by tiloyi** [comment]
Hi @AlexFe96 , it's released => https://mozaic.adeo.cloud/Components/Loader/

**Comment by tiloyi** [comment]
Hi @AlexFe96 ,
We offer the loader without the overlay as well.

As you can see in this preview => https://mozaic.adeo.cloud/previews/Components/Loader/previews/themes.html

This should allow you to do whatever you want inside the button.

The loader that we add in the design system can be used in several sizes and themes. More info [here](https://mozaic.adeo.cloud/Components/Loader/code/#variations).

And finally, another **LoadingButton** component will come later, but it's not completely planned yet. So in theory for now with the new Loader component you can already achieve the desired result.

Don't hesitate to let me know if you want to have a phone call to discuss this.
