### ISSUE TITLE
Add possibility to push value at initialization of auto complete

### ISSUE THREAD

**Issue by estgomez** [adeo/mozaic-design-system#1169]
# 🚀 Pattern enhancement proposal

### What kind of enhancement are you proposing ?
	
- [ ] On sketch file
- [ ] On Documentation
- [X] On source code

### Description
Actually, the only possibility to change the input value is with the watch on modelValue. However, for our (IPAO) behavior, we need to put a value inside the field at the initialization of the auto complete component.

For now, I have copy the mozaic auto complete to make my custom auto complete with the state.itemDisplayed initialization like this :
const state = reactive({
  open: false,
  itemListForDropdown: props.items,
  selected: props.modelValue,
  itemDisplayed: props.modelValue && props.modelValue.length > 0 ? props.modelValue[0].value : '',
  tagWidth: '0px',
});

### Justification
In our case, our form may be complete at the initialization because we use draft to save form state before leaving the screen. When a draft is existing, we complete the form before the form display.
So in our case, we need to put a value inside the input of the auto complete at the initialization.

**Anything else relevant?**

**Comment by tiloyi** [comment]
Hi @estgomez ,
Thank you for creating this outcome.

However I to close it here, as it concerns [Mozaic-Vue](https://github.com/adeo/mozaic-vue) and not the Mozaic core packages.

I took the liberty of taking your text and creating [a new issue on the appropriate repo](https://github.com/adeo/mozaic-vue/issues/828).
