### ISSUE TITLE
Stepper visual bug, when returning to past validated step

### ISSUE THREAD

**Issue by Jupoulet** [adeo/mozaic-design-system#1173]
# 🐞 Styleguide bug report

### Is this a regression?

No

### Description

Hello mozaic team :wave:
I found a miss-conception in your Stepper component, I'll try to explain the issue:
You have a css rule in mozaic that said: if the stepper item is **valid** AND if its not the **current** stepper item, then set the **stepper-item::after** background color to **green** .
This is a problem when the user can go back on the stepper. For example user is on step 3 (step 3 is current and not validated), step 1 and step 2 are validated. If I go back to step 1, step 1 become my current step but that does not mean that the step is not valid anymore.
The css selector is the following:
`.mc-stepper__item--validated:not(.mc-stepper__item--current)::after { background-color: green }`
In my opinion the rule should be: as long my stepperItem, ::after bg color should be colored event if its the current step.
```
.mc-stepper__item--validated::before,
.mc-stepper__item--validated::after {
  background-color: green;
}
```

## 🔬 Steps to reproduce the issue

Create a 3 step stepper. The 3 steps must be validated and the first step is your current step. You should be able to see the visual bug

## 🌍 Your Environment

Working in react projects
```
    "@mozaic-ds/css-dev-tools": "^1.29.1",
    "@mozaic-ds/icons": "^1.36.2",
    "@mozaic-ds/react": "1.3.0-beta.9",
    "@mozaic-ds/styles": "^1.29.1",
    "@mozaic-ds/web-fonts": "^1.22.0",
```

**Comment by tiloyi** [comment]
Hi @Jupoulet ,
Thanks for your message.

It is not a bug of the component.
I think that here, it is more a problem of vision/conception about how the component should behave.

In our vision, the position that has been chosen is to say that once a user comes back to a previous step, the following steps cannot be considered as still valid.

The Stepper is considered as a navigation element, just like a breadcrumb or a pagination; and in fact, on these components, you can't go back while maintaining the state of the page you just left.

I'm available on Slack if you want to talk about it in detail :)
