### ISSUE TITLE
Font-weight difference between adeo and LM preset

### ISSUE THREAD

**Issue by pLennyTudeAdeo** [adeo/mozaic-design-system#1221]
### Package version

@mozaic-ds/mozaic-web-components1.0.0-rc22

### Description

On the Adeo web-components preset, there is some font-weight differences.
Here an exemple with the m-datatable component :

Adeo preset :
<img width="2869" alt="image" src="https://user-images.githubusercontent.com/102951727/194575666-50b97b55-e530-47d7-8197-9ebd1301cc68.png">

LM preset (default):
<img width="2868" alt="image" src="https://user-images.githubusercontent.com/102951727/194575863-907544d7-a05c-421c-a52d-07623298688b.png">

As we can see, the title (th of the datatable), the badge text or the amount of items in the pagination doesn't gave the same font-weight.

If you try to change the font-weight dynamically in the inspector it doesn't work with the adeo preset so maybe there is a problem with the Roboto font weights ? (we can also see on the LM preset, if we change the font-weight it's ok).

**Comment by caqueste** [comment]
@tiloyi @mohamedMok Need to investigate components that use specific font-weight
