### ISSUE TITLE
feat(accordion): keep the border bottom after title rather than after content

### ISSUE THREAD

**Issue by mohamedMok** [adeo/mozaic-design-system#1335]
### I want to propose an evolution/improvement on

Component

### Description

![324467253_1350759142350795_6650393000894290397_n](https://user-images.githubusercontent.com/7878860/213666271-53da1f16-78c1-4ae3-891a-2d3b605eeb93.png)

**Comment by tiloyi** [comment]
Hi @caqueste , Hi @mohamedMok ,
Is this issue still relevant?

**Comment by tiloyi** [comment]
**Seen with @caqueste :**
As this need is not in great demand by the teams, there is no real reason to make the component evolve in this sense.

Teams that really need to have this kind of display can put a divider on the accordion content.

So I'm closing this issue.
