### ISSUE TITLE
Add a horizontal navigation menu (header/footer)

### ISSUE THREAD

**Issue by jared201** [adeo/mozaic-design-system#1338]
### I want to propose an evolution/improvement on

Component

### Description

Please add a horizontal navigation header menu component. It seems to be missing in the design system.

### Describe the solution you would like

it can be custom component with the possible semantics:

```
<navbar-header>
   <navbar-menu class="left-side">
      <navbar-menu-item>Home</navbar-menu-item>
      <navbar-menu-item>About</navbar-menu-item>
   </navbar-menu>
   <navbar-menu class="right-side">
      <navbar-menu-item>Profile</navbar-menu-item>
      <navbar-menu-item>Login</navbar-menu-item>
   </navbar-menu>

</navbar-header>
```

### Describe the alternatives you considered

current workaround is to build a template div that can be snapped on top use the Link component for the menu items

**Comment by mohamedMok** [comment]
Hello @jared201, 
Thanks for your feedback, 

We are glad that you are using/testing our design system. 

We would love to see what you are building with Mozaic. How did you hear of us? 

Which technology are you working on?

**Comment by jared201** [comment]
> Hello @jared201, Thanks for your feedback,
> 
> We are glad that you are using/testing our design system.
> 
> We would love to see what you are building with Mozaic. How did you hear of us?
> 
> Which technology are you working on?

I haven't worked on Mozaic yet, I just learned it from Github Explore since I've forked other design systems such as IBM's Carbon Design System which I plan to use for healthcare development projects. I have build something from near-scratch called Beef Design System based on Vue and Bulma.io and is used , I'm still exploring which industry Mosaic can fit nicely.

**Comment by mohamedMok** [comment]
Sounds great, we hope you found some exciting reading 😄 
Mozaic is Adeo's design system, it's used widely on e-commerce websites (e.g Leroy Merlin) and collaborator platforms (Web app). 

On top of the design system, we offer several libraries that implement our components in Vue, React, and Web-component. 

Let us know if you are looking to use the DS and need onboarding. Otherwise, could we close the issue?

**Comment by jared201** [comment]
> Sounds great, we hope you found some exciting reading 😄 Mozaic is Adeo's design system, it's used widely on e-commerce websites (e.g Leroy Merlin) and collaborator platforms (Web app).
> 
> On top of the design system, we offer several libraries that implement our components in Vue, React, and Web-component.
> 
> Let us know if you are looking to use the DS and need onboarding. Otherwise, could we close the issue?

Sure , you can close the issue. Thanks
