### ISSUE TITLE
Selection on m-checkbox-group

### ISSUE THREAD

**Issue by HeleneVermaut** [adeo/mozaic-design-system#1341]
### I am opening an issue for

Component

### Package version

@mozaic-ds/vue: "0.32.3"

### Description

Usecase: When you use m-checkbox-group and you have at the beginning a checkbox selected and you want to select another item, the selected values are reset.

### What happened?

![chrome_T5RaPeVZWB](https://user-images.githubusercontent.com/53294811/214521668-cd2fae00-94e4-4715-9524-d6e257d63299.png)
![chrome_EWFgBjJjXW](https://user-images.githubusercontent.com/53294811/214521672-bbd2a0cb-91f8-4156-8de4-f20c16afb23b.png)

### What is expected?

Expected: When you select another value, don't reset the selected values

### Code example

```HTML
<m-checkbox-group
              legend="lalala"
              :options="[
                {id:'id1', label: 'label1', value: 'v1'},
                {id:'id2', label: 'label2', value: 'v2'}
              ]"
              inline
              v-model="checkedValues"
            />
```

### Is this a regression?

- [ ] Yes
- [ ] No
- [X] I don't know

**Comment by tiloyi** [comment]
Fixed in [@mozaic-ds/vue@0.37.1](https://github.com/adeo/mozaic-vue/releases/tag/%40mozaic-ds%2Fvue%400.37.1)
