### ISSUE TITLE
Stepper : Change colors for accessibility

### ISSUE THREAD

**Issue by matthieu-castier** [adeo/mozaic-design-system#1348]
### I want to propose an evolution/improvement on

Design Tokens

### Description

The background-color of steppers aren't valid with the WCAG AA.

![image](https://user-images.githubusercontent.com/52412589/216013994-90527255-f46d-4ecc-8fe4-173b8f1331b8.png)

### Describe the solution you would like

In `packages/tokens/build/scss/_tokens.scss` change the value of : 
- $color-stepper-item-current-background
- $color-stepper-link-hover-text
- $color-stepper-indicator-current-background
- $color-stepper-indicator-current-border
- $color-stepper-icon
- $color-stepper-title

Old value : #46a610
New value: #188803 ($color-primary-01-600)

![image](https://user-images.githubusercontent.com/52412589/216014825-3eecbee2-e97d-403b-b32b-196eb78cad8f.png)

**Comment by tiloyi** [comment]
Hi @matthieu-castier ,
Thanks for your issue, we will take care of it.

**Comment by tiloyi** [comment]
Hi @caqueste , 
I'm tagging you, because we're going to need design recommendations on this.

**Comment by florencemcd** [comment]
@tiloyi do you have an update on this please ?

**Comment by tiloyi** [comment]
Hi @florencemcd the point is on the design side.
I think it's up to @caqueste to tell us where he stands on that.

**Comment by caqueste** [comment]
Hello @tiloyi @matthieu-castier @florencemcd 👋 
Sorry for the delay, I had to cover the most important topics.

@tiloyi We can make a quick fix, so you can update the value of the tokens mentioned in the issue and change the `$color-primary-01-500` to `$color-primary-01-600`:
$color-stepper-item-current-background
~~$color-stepper-link-hover-text~~
$color-stepper-indicator-current-background
$color-stepper-indicator-current-border
$color-stepper-icon
$color-stepper-title

**Except this token : `$color-stepper-link-hover-text`, please change to `$color-grey-999`**

For the compact version, you can also change the value of the stepper title (Step 3/4) to `$color-primary-01-600`.
<img width="169" alt="Capture d’écran 2023-10-10 à 18 49 11" src="https://github.com/adeo/mozaic-design-system/assets/43212270/9ecda236-37ea-424b-b3e2-322d69370fed">

Thanks!
