### ISSUE TITLE
Action list - action

### ISSUE THREAD

**Issue by lisa-caffiers** [adeo/mozaic-design-system#1374]
### I am opening an issue for

Styles (CSS, SCSS, ...)

### Package version

@mozaic-ds/styles: 1.53.0

### Description

Technical definition

There is a difference in typo size between Figma and Mozaic CSS classes for the DataTable values.

**POF Action list** : 

https://offer.sit.kobi.adeo.cloud/product-offer-family/display-view 

https://www.figma.com/file/UpJZh8SFuF5bGA5NUH3ukU/Product-Offer-Family?node-id=3283%3A113740&t=91u12vhJhUxdFuD1-0

**Action** : 
Figma: #191919
CSS: #1e1e1c

![image](https://user-images.githubusercontent.com/92927973/221232243-658178f0-f2ee-4699-8af8-a2995c838086.png)

### To Reproduce

1. Go to the POFS screen
2. Click on the Actions button
3. I'm able to see the Action list: The color is not the same as Figma component

### Is this a regression?

- [ ] Yes
- [ ] No
- [ ] I don't know

**Comment by tiloyi** [comment]
Fixed by https://github.com/adeo/mozaic-vue/pull/1134
