### ISSUE TITLE
[styles] mc-tag padding

### ISSUE THREAD

**Issue by mdebieAdeo** [adeo/mozaic-design-system#1412]
### I am opening an issue for

Styles (CSS, SCSS, ...)

### Package version

"@mozaic-ds/styles": "1.56.0"

### Description

My UX colleague reported to me that the tags we're using don't comply with the Figma files. The horizontal padding between text and border is 23px instead of 24px.
<img width="740" alt="Capture d’écran 2023-04-05 à 14 57 01" src="https://user-images.githubusercontent.com/103485932/230087207-4e0a3d46-e2b5-4c52-bbce-b79d86a444eb.png">

### Mock-up(s)

https://www.figma.com/file/PkQLYkxi4BLU5SA8WgxmCU/Collaborator-portal?node-id=9095%3A261994&t=92qAmwEECwVKc4GU-1

### Is this a regression?

- [ ] Yes
- [ ] No
- [x] I don't know

**Comment by caqueste** [comment]
Thanks @mdebieAdeo, we'll fix it 😉
