### ISSUE TITLE
[styles] - Flag label - on Safari +16.4

### ISSUE THREAD

**Issue by Hatem-Mansour** [adeo/mozaic-design-system#1451]
### I am opening an issue for

Styles (CSS, SCSS, ...)

### Package version

@mozaic-ds/styles@1.62.0

### Description

On Safari +16.4 the flag of discount on price showing on tow lines (example on ES bu , but i think for all other BUs)
https://www.leroymerlin.es/productos/ofertas/viva-el-verano/

the property to check is  box-decoration-break: clone;  on mc-flag__label 

### Is this a regression?

- [ ] Yes
- [ ] No
- [ ] I don't know

**Comment by tiloyi** [comment]
Hi @Hatem-Mansour , Hi @mohamedMok ,
I don't have any news.
Allow me to close this issue.

Feel free to reopen it if you need to ;)
