### ISSUE TITLE
Fields + option buttons : missing margin

### ISSUE THREAD

**Issue by matthieu-castier** [adeo/mozaic-design-system#1462]
### I am opening an issue for

Styles (CSS, SCSS, ...)

### Package version

@mozaic-ds/styles": "1.60.0

### Description

In a form, when an option buttons follow a label, there isn't any margin.

### GitHub repository

https://github.com/adeo/cdp-due--lmfr-services-lead-page-module

### Mock-up(s)

https://www.leroymerlin.fr/servicesleadpage/services/standardleadpageapp/step/1?leadType=POSE_DE_POELE_PRIME_RENOV&subType=POSE_DE_POELE_A_GRANULES

### Is this a regression?

- [ ] Yes
- [ ] No
- [X] I don't know

**Comment by tiloyi** [comment]
Resolved by: https://github.com/adeo/mozaic-freemarker/pull/237
