### ISSUE TITLE
Strange elastic animation with layer

### ISSUE THREAD

**Issue by paulinelapierreadeo** [adeo/mozaic-design-system#1521]
### I am opening an issue for

Component

### Package version

?

### Description

Hi, when I click on “apply a discount” on [leroymerlin.fr](http://leroymerlin.fr/) I have a strange animation around the layer. I have like an elastic animation. I reproduce this comportment on Safari MacOS

(Reporting from Rémi KACZMAREK)

### To Reproduce

https://github.com/adeo/mozaic-design-system/assets/142427206/0ceccb7b-e734-4c46-9cc3-c0b2e93625bd

### Is this a regression?

- [ ] Yes
- [ ] No
- [X] I don't know

**Comment by paulinelapierreadeo** [comment]
For more details :
MacOS 14.1 (23B74)
Safari : Version 17.1 (19616.2.9.11.7)

**Comment by mohamedMok** [comment]
Hello @paulinelapierreadeo, 

Thanks for your issue, can you please share with us the link to the repo to check the implementation. 
After some testing I realized that all layer on `leroymerlin.fr` works fine.

**Comment by mohamedMok** [comment]
This bug didn't came from the DS. It seems fixed now
