### ISSUE TITLE
fix(Tooltip): make tooltip usable by keyboard for accessibility

### ISSUE THREAD

**Issue by LucasFournier17** [adeo/mozaic-design-system#1545]
### I am opening an issue for

Styles (CSS, SCSS, ...)

### Package version

@mozaic-ds/styles@1.70.2

### Description

To make the `Tooltip` component usable by keyboard, we need to display it when the component receives focus from keyboard navigation. Today, there is no possibility for keyboard-only users to see the `Tooltip`.

### What is expected?

To display the Tooltip when the component receives focus from keyboard navigation.

### Is this a regression?

- [ ] Yes
- [X] No
- [ ] I don't know

**Comment by tiloyi** [comment]
Fixed by #1546
