### ISSUE TITLE
Able to remove the shadow on MDatatableV2

### ISSUE THREAD

**Issue by JonathanSclavonLM** [adeo/mozaic-design-system#1547]
### I want to propose an evolution/improvement on

Component

### Description

Hello, 

in the dopanim project, we have a DataTable with rows who have an expandable other datatable.

(ref to the screenshot below)

<img width="1331" alt="Capture d’écran 2024-02-06 à 16 38 06" src="https://github.com/adeo/mozaic-design-system/assets/139749617/47d3bf9c-4fa8-4d3c-9e63-213728b83832">

The entire screen: 

<img width="1394" alt="Capture d’écran 2024-02-06 à 16 40 33" src="https://github.com/adeo/mozaic-design-system/assets/139749617/0bdf5518-a1a4-460f-add7-4fe1a6dc773b">

### Describe the solution you would like

We want to have the ability to remove the box-shadow property on the MDataTableV2

**Comment by tiloyi** [comment]
Hi @JonathanSclavonLM ,
Thanks for your message.

In order to process your request, I would need some additional information, please.

Could you tell me whether you're on a DataTableV1 or DataTableV2?

**Comment by JonathanSclavonLM** [comment]
> Hi @JonathanSclavonLM , Thanks for your message.
> 
> In order to process your request, I would need some additional information, please.
> 
> Could you tell me whether you're on a DataTableV1 or DataTableV2?

Hello, its on DataTableV2

**Comment by tiloyi** [comment]
Hi @JonathanSclavonLM ,
This issue is treated by the following PR => https://github.com/adeo/mozaic-vue/pull/1924

**Comment by tiloyi** [comment]
Available in [@mozaic-ds/vue-3@0.61.0](https://github.com/adeo/mozaic-vue/releases/tag/%40mozaic-ds%2Fvue-3%400.61.0)
