### ISSUE TITLE
Words in a sentence inside a tooltip are cut

### ISSUE THREAD

**Issue by shunny13** [adeo/mozaic-design-system#1551]
### I am opening an issue for

Component

### Package version

@mozaic-ds/vue@0.51.0

### Description

Hello,
We are using Vue2 and when we are having sentences in the tooltip , the words are cut. 
![image](https://github.com/adeo/mozaic-design-system/assets/45214857/5372de5d-2bea-4cfd-9f2c-9bc2e5ec6956)

![image](https://github.com/adeo/mozaic-design-system/assets/45214857/5453e860-4cb2-4320-a873-801ed8402aeb)
Can you help us or give us a quickfix solution ? Maybe we didn't implement the component correctly
Thank you

### Is this a regression?

- [ ] Yes
- [ ] No
- [X] I don't know

**Comment by tiloyi** [comment]
Hi @shunny13 ,
Thanks for your message.

Unfortunately, we're not going to be able to correct this.
What you want to do goes against the rules for using this component.

As indicated in the [component documentation](https://mozaic.adeo.cloud/components/tooltip/#usage): **"The tooltip text must be short (1 or 2 lines maximum)"**.

As a result, using several sentences in this component is not recommended.

So, I recommend that you as your designer to get in touch with our UI Lead, @caqueste , to see what can be done to find another solution for your situation.
