### ISSUE TITLE
Create PayPo and OneyRaty icons (monochrome + coloured)

### ISSUE THREAD

**Issue by rlacrosse-adeo** [adeo/mozaic-design-system#1615]
### I want to propose an evolution/improvement on

Icon set

### Description

Hello,

Can you add the icons for:
- PayPo
- Oney Raty

Please.

Refer to https://jira.adeo.com/browse/TMPO-6767 or in the Initiative https://jira.adeo.com/browse/CCDP-1200 for further information.

**Comment by rlacrosse-adeo** [comment]
Hello,
The monochrome are still missing. LMPL is about to test the feature in UAT.

**Comment by caqueste** [comment]
Hello @rlacrosse-adeo, please wait for the October update which will include the PayPo logotype. The OneyRaty logotypes is already available.
FYI, adding icons to V1 isn't our priority as we are focused on version 2. 
However, if it's urgent, adding the logos locally to your product is a solution as this is only a SVG.

**Comment by caqueste** [comment]
https://github.com/adeo/mozaic-design-system/releases/tag/v1.78.0
