### ISSUE TITLE
Create ApplePay icons (monochrome)

### ISSUE THREAD

**Issue by SarahVimeux** [adeo/mozaic-design-system#1616]
### I want to propose an evolution/improvement on

Icon set

### Description

Create ApplePay icons (monochrome)

**Comment by caqueste** [comment]
Hello @SarahVimeux, We close the issue as the Apple Pay logotype can't be added in a monochrome version as only the artwork provided by Apple can be used.
→ https://developer.apple.com/apple-pay/marketing/
