### ISSUE TITLE
[CRITICAL] packages with bin scripts cannot be installed on windows

### ISSUE THREAD

**Issue by jamy-lm** [adeo/mozaic-design-system#431]
# 🐞 Pattern bug report

### Where did you experience this bug ?
	
- [ ] On sketch file
- [ ] On Documentation
- [x] On source code

### Is this a regression?
No

### Description

On `@mozaic-ds/styles` install, on windows, an error is throwed.
On windows, files cannot be created with `:` in their name.
All bin declared in mozaic command contains `:`

## 🔬 Steps to reproduce the issue
On windows, install an app with `@mozaic-ds/styles` dependency

## 📷 Screenshot (optional - it might be a gif) or Sketch file (if existing)
![image](https://user-images.githubusercontent.com/46380750/69222726-577dcf80-0b7a-11ea-8bca-63543dabb6f3.png)

## 🔥 Exception or Error
<pre>npm ERR! syscall symlink
npm ERR! path ../@mozaic-ds/tokens/bin/build.js
npm ERR! dest /mnt/c/Users/***/node_modules/.bin/mozaic-tokens:build
npm ERR! errno -22
npm ERR! EINVAL: invalid argument, symlink '../@mozaic-ds/tokens/bin/build.js' -> '/mnt/c/Users/***/node_modules/.bin/mozaic-tokens:build<code>
</code></pre>

## 🌍 Your Environment
Caused on windows

**Anything else relevant?**
Hello, 
We absolutely NEED this to work on all platform **today**.
Because it's a **prerequisite** to mozaic migration planified for 25+ coworkers and 7 feature teams in 5 days.
This step is mandatory before launching LeroyMerlin Common Digital Platform due to spring 2020

**Comment by gael-boyenval** [comment]
Okay, I will make a fix today and try to release it today also.

**Comment by jamy-lm** [comment]
Merci !
ps : joli nom de branche ! ;-)

**Comment by jamy-lm** [comment]
Problem solved !

Thanks
