### ISSUE TITLE
feat(refactor/setting-tools): improve adding the mixin demo-state-class

### ISSUE THREAD

**Issue by marineFabien** [adeo/mozaic-design-system#473]
# 🚀 Styleguide feature request

### Description
Is it possible to improve the use of the mixin demo-state-class?
If you are only a consumer of Mozaic and not a contributor, you have to add this dev mixin. Indeed, this mixin is used only for refactoring code generated for the previews.

### Describe the solution you'd like
For example, LM doesn't use the same build as Mozaic, so it would be perfect if we could have the choice to use this mixin or not, but actually it's inseparable of few components like the links.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by gael-boyenval** [comment]
don't you import `all-settings` ?

**Comment by marineFabien** [comment]
> don't you import `all-settings` ?

Not Yet :p
