### ISSUE TITLE
Wrong var names for spacings

### ISSUE THREAD

**Issue by MDELLIDJ** [adeo/mozaic-design-system#474]
# 🐞 Pattern bug report

### Where did you experience this bug ?
	
- [ ] On sketch file
- [x] On Documentation
- [ ] On source code

### Is this a regression?

No

### Description

In the documentation, the spacing variables contain dashes, if we use it it makes the compilation to crash. I noticed they don't need dashes. 

e.g `$mu-150` should be `$mu150`

## 🔬 Steps to reproduce the issue

Write `$mu-150` or any other space variable in a SASS file.

**Comment by tiloyi** [comment]
Hi,
Thanks for bringing that up.
There is indeed an error in the documentation.

We'll correct it right away.

But you're right, the correct use of the variables of the magic-unit, is without dashes : `$mu025`, `$mu150`, etc...
