### ISSUE TITLE
Button label not vertically aligned

### ISSUE THREAD

**Issue by ysellamiLM** [adeo/mozaic-design-system#495]
Label with class `mc-button__label` in a `mc-button` not vertically aligned with an adjacent icon in the same button.

Version used : `1.0.1-beta.0`
![mozaic-button-vertical-align](https://user-images.githubusercontent.com/55577803/75907504-b1b05100-5e48-11ea-81da-881d7dd97c96.png)

**Comment by caqueste** [comment]
Hello @ysellamiLM 
It's not the good font, you're using the Arial font.
Have you imported the font settings? → http://mozaic.adeo.cloud/GetStarted/Developers/usingStaticAssets/

Check with the good font, and we will find the solution if it's not fixed.

**Comment by ysellamiLM** [comment]
Thanks for your prompt reply, after looking more into it, it seems more related with a different issue which does not allow the loading of the required fonts.
Sorry to have bothered you with that.
