### ISSUE TITLE
Add a "pointer-events: none;" a .mc-button__label

### ISSUE THREAD

**Issue by MathieuLgrs** [adeo/mozaic-design-system#497]
# 🐞 Styleguide bug report

### Is this a regression? no

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

When we click on the button the event is done on the span and not on the button and generates an error

## 🔬 Steps to reproduce the issue

https://leroymerlin.kobi-gluer-frlm-web-team-product-01-qa.apps.op.acp.adeo.com/v3/p/produits/terrasse-jardin/parasol-tonnelle-et-voile-d-ombrage/moustiquaire-l1400990570?page=1

In the price filter of family pages on the "Apply" button, the event does not trigger

## 📷 Screenshot (optional - it might be a gif)

![screen](https://user-images.githubusercontent.com/52403941/76093297-05de4100-5fc1-11ea-87da-898ed7b36be0.png)

## 🔥 Exception or Error
![error](https://user-images.githubusercontent.com/52403941/76093412-31f9c200-5fc1-11ea-9bea-404dbd4d342d.PNG)

In the browser console, this generates an error

## 🌍 Your Environment

on the qualif environment

**Anything else relevant?**

All browsers

**to fix this, in the file "_c.button.scss", add a "pointer-events: none;" on "& __ label"**

**Comment by MathieuLgrs** [comment]
to fix this, in the file "_c.button.scss", add a "pointer-events: none;" on "& __ label"

**Comment by tiloyi** [comment]
@MathieuLgrs As we talked about it together Friday on Slack, there are two ways to solve your problem:

1. On the Mozaic side, as you suggested by adding a `pointer-events: none;` on the span
2. OR in your JS code, using the Javascript property **Event.currentTarget**, to target only the element to which your event is attached.

Concerning solution #1, if you feel confident enough, you can contribute directly to Mozaic by doing a PR to add the `pointer-events: none;` property.

The contribution process is documented in these pages: [http://mozaic.adeo.cloud/Contributing/Developers/](http://mozaic.adeo.cloud/Contributing/Developers/)

However, if you don't feel comfortable enough to do so, let me know and I'll make the correction in Mozaic.
