### ISSUE TITLE
PostCSS with Angular stylePreprocessorOptions not working together

### ISSUE THREAD

**Issue by C0ZEN** [adeo/mozaic-design-system#510]
# 🐞 Styleguide bug report

### Description

Configuring PostCSS with Angular CLI is not working as seen in the [documentation](http://mozaic.adeo.cloud/GetStarted/Developers/configurePostCss/#e-with-angular-cli) when using the [Style preprocessor options](https://angular.io/guide/workspace-config#style-preprocessor-options) to customize SCSS imports.

## 🔬 Steps to reproduce the issue

- Create a dummy SCSS file in the root directory of the project
- Configure `angular.json` build options to use the stylePreprocessorOptions
- Import this file in the app.component.scss file of the project
- Start the project

### Scaffolding

-- dummy.scss
-- src
---- app
------ app.component.scss

### angular.json

```
"stylePreprocessorOptions": {
   "includePaths": [
      "dummy"
   ]
},
```

### app.component.scss

```
@import 'dummy.scss';
```

## 🔥 Error

```
ERROR in Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: File to import not found or unreadable: dummy.
```

## 🌍 Your Environment

**Styleguide Version:**

```
"@mozaic-ds/css-dev-tools": "1.0.1-beta.3"
"@mozaic-ds/styles": "1.0.1-beta.5"
"@angular/core": "9.1.1"
"postcss-scss": "2.0.0"
```

**Comment by C0ZEN** [comment]
I found a workaround with the [Mozaic SASS custom paths](http://mozaic.adeo.cloud/GetStarted/Developers/Configuration/#sassincludepaths--array-of-paths).
I will provide a PR to include a warning about it nevertheless you could still to handle the support for this option to work seamlessly.

**Comment by C0ZEN** [comment]
PR provided.

**Comment by tiloyi** [comment]
Hello @C0ZEN , thank you for your issues and your PR. Sorry for the delay in my reply. Is there any way to get in touch with you, to discuss the points you've indicated?

**Comment by C0ZEN** [comment]
@tiloyi commenting the PR isn't enough?

**Comment by tiloyi** [comment]
@C0ZEN It's not necessarily about this particular PR. I just sent you an email ;)
