### ISSUE TITLE
Select component with icon

### ISSUE THREAD

**Issue by C0ZEN** [adeo/mozaic-design-system#523]
# 🚀 Styleguide feature request

### Description

Having a select component with options: icon and text.

### Describe the solution you'd like

Something similar to https://developer.snapappointments.com/bootstrap-select/examples/#icons

**Comment by mohamedMok** [comment]
Hi @C0ZEN,

We offer a dropdown usable with icons
https://v1290-dot-mozaic-design-system-dtrp.appspot.com/Components/Form/Dropdown/code/
