### ISSUE TITLE
Add two new icons

### ISSUE THREAD

**Issue by C0ZEN** [adeo/mozaic-design-system#525]
# 🚀 Styleguide feature request

### Description

I need top and bottom arrows designed as `Arrow_Back` and `Arrow_Next`.

### Describe the solution you'd like

Add one icon for the top arrow designed like the `Arrow_Back`.
Add one icon for the bottom arrow designed like the `Arrow_Back`.

**Comment by mohamedMok** [comment]
@C0ZEN 
The icons are now available 
https://v1290-dot-mozaic-design-system-dtrp.appspot.com/Foundations/Icons/catalog/
---
ArrowDown
ArrowTop
