### ISSUE TITLE
Card component

### ISSUE THREAD

**Issue by C0ZEN** [adeo/mozaic-design-system#526]
# 🚀 Styleguide feature request

### Description

Create a card component.

### Describe the solution you'd like

Create a card component.
Based on the usage case, it could lead to create multiple type of cards.

**Comment by caqueste** [comment]
Please can you send us examples and use cases?

**Comment by C0ZEN** [comment]
I am working on the LM Studio project and we have actually two "kind of the same" carousel:
- [home carousel](https://travaux.leroymerlin.fr/)
- [home SEA carousel](https://travaux.leroymerlin.fr/app/home?type=0003&city=Lille&zipCode=59000)

This would be better to let Mozaic define what is should look time at least.

**Comment by C0ZEN** [comment]
Here what we use for now on the LM Studio project:
- [https://i.imgur.com/SGvv9Ge.png](https://i.imgur.com/SGvv9Ge.png)
- [https://i.imgur.com/thMOlww.png](https://i.imgur.com/thMOlww.png)
- [https://i.imgur.com/gyJLkPP.png](https://i.imgur.com/gyJLkPP.png)
