### ISSUE TITLE
Carousel component

### ISSUE THREAD

**Issue by C0ZEN** [adeo/mozaic-design-system#527]
# 🚀 Styleguide feature request

### Description

Create a carousel component.

### Describe the solution you'd like

Create a carousel component.

**Comment by caqueste** [comment]
Please can you send us examples and use cases?

**Comment by C0ZEN** [comment]
I am working on the LM Studio project and we have actually two "kind of the same" carousel:
- [home carousel](https://travaux.leroymerlin.fr/)
- [home SEA carousel](https://travaux.leroymerlin.fr/app/home?type=0003&city=Lille&zipCode=59000)

This would be better to let Mozaic define what is should look time at least.
