### ISSUE TITLE
Sidebar component

### ISSUE THREAD

**Issue by C0ZEN** [adeo/mozaic-design-system#528]
# 🚀 Styleguide feature request

### Description

Create a sidebar component.

### Describe the solution you'd like

Create a sidebar component.

**Comment by caqueste** [comment]
Please can you send us examples and use cases?

**Comment by C0ZEN** [comment]
When clicking the hamburger menu (on small device) of this [page](https://travaux.leroymerlin.fr/app/home?type=0003&city=Lille&zipCode=59000), the sidebar is opened.
The [design](https://i.imgur.com/2QPbeH5.png) should be define by Mozaic I think.

**Comment by caqueste** [comment]
Yes, we can plan a scroll bar pattern for use cases with a height fixed bloc. In your case, a custom scroll bar is necessary?

**Comment by C0ZEN** [comment]
@caqueste in other words we need a drawer. So, yes and no. We do not need a custom scroll since the drawer act like a dialog: being on top of the main content.
The scrollbar is still native but only scroll the drawer content.
Like [here](https://i.imgur.com/z9BptwY.png).
