### ISSUE TITLE
Dependencies management

### ISSUE THREAD

**Issue by C0ZEN** [adeo/mozaic-design-system#530]
# 🚀 Styleguide feature request

### Description

There are amazing tools to handle the update of dependencies.

### Describe the solution you'd like

Configure [Renovate](https://github.com/apps/renovate) to handle the dependencies.

### Describe alternatives you've considered

Use [Snyk](https://snyk.io/) instead of [Renovate](https://github.com/apps/renovate).

I can provide a PR.

**Comment by mohamedMok** [comment]
Hi @C0ZEN 

Thanks for this comment, 

I had a quick look at both of the tools you were talking about. 
I feel more comfortable with Renovate at the moment. 

Feel free to submit a PR when you're ready 👍

**Comment by C0ZEN** [comment]
@mohamedMok will do. I also prefer Renovate and it is free for all types of projects.

**Comment by C0ZEN** [comment]
@mohamedMok could you add Renovate for this repository please?
Two clicks and done: https://github.com/marketplace/renovate
I will provide tomorrow a PR to configure Renovate.

**Comment by mohamedMok** [comment]
@C0ZEN, Will do! 
I need to go through the adeo process to add app in this repo.
I'll let you know how it goes :)

**Comment by C0ZEN** [comment]
@mohamedMok ok, I hope that this is a fast process as it should be.
Also, do you have a team created for this project?
Renovate can add people/teams for reviewers and assignees and a team is clearly the best option.

**Comment by mohamedMok** [comment]
I hope too!
Yes we do have a team for the project 
https://github.com/orgs/adeo/teams/design-system/

**Comment by C0ZEN** [comment]
@mohamedMok PR added. Containing additional information about the initial configuration I made. 

Two important notes here:
- Seems to me that this is a bit soon to auto merge patch PR due to only one GitHub action (no tests, no lint, no nothing...). I could disable the auto merge.
- Could be better to have a dedicated team to handle the Renovate PR.

**Comment by C0ZEN** [comment]
Associated PR closed due to another solution used.
Closing.
