### ISSUE TITLE
Version management

### ISSUE THREAD

**Issue by C0ZEN** [adeo/mozaic-design-system#531]
# 🚀 Styleguide feature request

### Description

Instead of handling the versions by hand a tool could be used to leverage this (and kill all humans).

### Describe the solution you'd like

Configure [Semantic Release](https://github.com/semantic-release/semantic-release) to handle the tag management, release notes, GitHub labels on the issues/PR, publish to npm/GitHub, etc...
Add the Semantic Release badge in the README.md.

I can provide a PR.

**Comment by C0ZEN** [comment]
Not so sure if this is so "easy" since you have multiple npm packages.
Does all packages are in different repositories or not?

**Comment by mohamedMok** [comment]
Hi @C0ZEN, 

Thanks for your comment! 
The process is automated today for the tag management, release note, publishing on npm and Github. 
Unfortunately, we are not following the semantic versioning as we should. 
We are releasing manually to have control of every version published and serve. 

We will take care of that once we have our first stable version.
