### ISSUE TITLE
Contributing hall of fame

### ISSUE THREAD

**Issue by C0ZEN** [adeo/mozaic-design-system#532]
# 🚀 Styleguide feature request

### Description

This is always good to give credits and what is better than a hall of fame for your contributors?

### Describe the solution you'd like

Configure [All Contributors](https://github.com/all-contributors/all-contributors) for GitHub.

I can provide a PR.

**Comment by caqueste** [comment]
Hello @C0ZEN ! We agree with you.
We planned this feature for the website ;)

**Comment by C0ZEN** [comment]
Someone with admin rights must add the [contributors Github app](https://allcontributors.org/docs/en/bot/installation).

**Comment by C0ZEN** [comment]
PR provided.
