### ISSUE TITLE
Labelizing issues when associated with PRs

### ISSUE THREAD

**Issue by C0ZEN** [adeo/mozaic-design-system#548]
# 🚀 Styleguide feature request

### Description

When adding a PR to fix an issue it could be better to have a label indicating the state of the PR.
This is an useful information.

Could have three labels:

- one added once a PR is opened
- one added once a PR is rejected
- one added once a PR is merged

Adding a label should remove the others.

**Example:**

Creating a PR will add a label "opened".
Merging the PR will remove the label "opened" and add the label "merged".

### Describe the solution you'd like

Use a GitHub application to handle the labels.
I could provide a PR for that.
Mention me to do so.

### Describe alternatives you've considered

DIY.

**Comment by mohamedMok** [comment]
Hi @C0ZEN 
It's a great idea, we are not planning to add it! Feel free to provide a PR. 
Thanks!

**Comment by C0ZEN** [comment]
@mohamedMok PR provided.
An action on your hand is required to install the GitHub application handling the labels.
Also once shipped you could add me as a contributor for more stuff (@all-contributors add @C0ZEN for ideas, tool and code) by commenting this issue or the PR directly.

**Comment by mohamedMok** [comment]
Hi @C0ZEN 

Github Application is installed and the PR is merged. 

@all-contributors please add @C0ZEN  for ideas, tool and code
