### ISSUE TITLE
[Help wanted] How to enable the PostCSS production on Angular?

### ISSUE THREAD

**Issue by C0ZEN** [adeo/mozaic-design-system#553]
# 🚀 Styleguide feature request

### Description
Based on the [documentation to compile PostCSS on production](http://mozaic.adeo.cloud/GetStarted/Developers/configurePostCss/#compiling-for-production), I should set an environment variable.
I did not manage to find out a way to do it yet for Angular.
Any help is welcome.

### Describe the solution you'd like
Based on the solution, you could update the documentation to describe how to do it.

**Comment by mohamedMok** [comment]
Hello @C0ZEN 

Let me know how is it going? 
The environment variable will give you access to the Production version of our plugins (minified..) 
Without it should still work. 

Maybe you could have a similar approach? 
https://www.chrisjmendez.com/2017/05/24/using-dotenv-with-angular/

**Comment by C0ZEN** [comment]
@mohamedMok the article you linked is related to the JavaScript environment.
PostCSS uses the system environment.
I found [this article](https://medium.com/@fidelisclayton/system-environment-variables-in-angular-1f4a922c7b4c) and will give it a shot soon.

**Comment by C0ZEN** [comment]
@mohamedMok Following [this article](https://medium.com/@fidelisclayton/system-environment-variables-in-angular-1f4a922c7b4c) but this is not working.
Also, I tried to use [cross-env](https://www.npmjs.com/package/cross-env) to set the environment variable during the `npm run build` command nevertheless it seems that this is not working.
Can you confirm to me that when the mozaic environment is in production the linter should not be runned? I based my analysis on the fact that this step should not be part of the production. Could be cool to have a log indicating which environment is used when using PostCSS.

**Comment by mohamedMok** [comment]
Hi @C0ZEN
Sorry for the late answer! We will add the log with the environment information shortly.
