### ISSUE TITLE
Wrong example to implement borders in documentation code

### ISSUE THREAD

**Issue by marineFabien** [adeo/mozaic-design-system#573]
# 🐞 Styleguide bug report
### Description
http://mozaic.adeo.cloud/Foundations/BorderRadius/code/
In this page, regarding the basic example, i think that it is wrong, it should be more like that: 
```
.example {
    border-radus: get-border-radius(s);
    border-radus: get-border-radius(m);
    border-radus: get-border-radius(l);
}
```
instead of this actual example: 
```
.example {
    @include set-border-radius('s');
    @include set-border-radius('m');
    @include set-border-radius('l');
}

```
because the code generated is as below:
https://github.com/adeo/mozaic-design-system/blob/master/packages/styles/settings-tools/_s.border.scss
 A clear and concise description of the problem...

**Comment by tiloyi** [comment]
@marineFabien Indeed, the **set-border-radius** mixin, directly generates the `border-radius:` property, without the need to specify it.

Therefore the following code: 
`border-radus: get-border-radius(s);`

is the equivalent of `@include set-border-radius('s');`

However, you are right, the documentation is not clear on this. So I'm going to update the documentation to make it easier to understand.
