### ISSUE TITLE
Swift Design token not updated

### ISSUE THREAD

**Issue by MrCloud** [adeo/mozaic-design-system#624]
# 🐞 Pattern bug report

### Where did you experience this bug ?
	
- [x ] On source code

### Is this a regression?

no, is the generation of this file in use today or was it only generated at the time its support was enabled in the project ?
### Description

https://github.com/adeo/mozaic-design-system/blob/master/packages/tokens/build/ios/StyleDictionaryColor.swift has not been updated to include latest design token colors.

**Comment by mohamedMok** [comment]
@all-contributors please add @MrCloud for bug and ideas
