### ISSUE TITLE
Add a "Duplicate" icon

### ISSUE THREAD

**Issue by gaetan-delaville** [adeo/mozaic-design-system#662]
# 🚀 Pattern enhancement proposal

### What kind of enhancement are you proposing ?
	
- [X] On sketch file
- [X] On Documentation
- [ ] On source code

### Description
A "Duplicate" icon

### Justification
We need the user to be able to duplicate elements on our interface,
and we have no clear icon to indicate this possibility

**Anything else relevant?**
Example here https://akveo.github.io/eva-icons/#/?searchKey=duplicate&type=outline
<img width="128" alt="Capture d’écran 2020-11-05 à 15 00 12" src="https://user-images.githubusercontent.com/54271769/98250410-abdeb280-1f77-11eb-82dc-389d600808de.png">

**Comment by nherwegh** [comment]
Hello, @gaetan-delaville 
we have this icon in the Sketch icon kit, we just need to update the icon kit on GitHub. It's coming very soon.
Good day.

**Comment by gaetan-delaville** [comment]
Great news :) Looking forward to the new release.
Good day to you too !
