### ISSUE TITLE
Bug on link with icons

### ISSUE THREAD

**Issue by matthieu-castier** [adeo/mozaic-design-system#684]
# 🐞 Styleguide bug report

### Is this a regression?

 I don't know.

### Description

 On mobile, when you have a link with an icon, it is not at the right size depending on the amount of text.

## 🔬 Steps to reproduce the issue
Go on https://www.leroymerlin.fr/services/ in mobile device view.
Swipe the content in "Tous nos services" to "Apprendre à bricoler". 
You will see that the icons are not all the same size.
 

## 📷 Screenshot (optional - it might be a gif)
![image](https://user-images.githubusercontent.com/52412589/100082574-affc4280-2e48-11eb-8520-0f98d2dd828f.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment

**Styleguide Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by tiloyi** [comment]
Hi @matthieu-castier ,
I have just created a PR that corrects the problem.
I've put you as a reviewer of this PR, can you take a look at it and validate if the proposed solution suits you?
