### ISSUE TITLE
No label for date picker input

### ISSUE THREAD

**Issue by yannkozon** [adeo/mozaic-design-system#708]
# 🐞 Pattern bug report

### Where did you experience this bug ?
	
- [ ] On sketch file
- [x] On Documentation
- [x] On source code

### Description

There is no `<label>` for date picker input.

**Comment by tiloyi** [comment]
Hello @yannkozon ,
Thank you for your feedback.

In fact, it is possible to use a label with each element of the form, using the Field element.
You will find the documentation here : https://mozaic.adeo.cloud/Components/Form/Field/

**Comment by yannkozon** [comment]
Hello @tiloyi ,

Yes it's possible but it's required to use `<input>` and in exemple there is no `<label>`.
An exemple with valid code is better.

**Comment by tiloyi** [comment]
> Hello @tiloyi ,
> 
> Yes it's possible but it's required to use `<input>` and in exemple there is no `<label>`.
> An exemple with valid code is better.

In fact, the example with the label + input, is in the Field component: https://mozaic.adeo.cloud/Components/Form/Field/
But you're right, the documentation may not be explicit enough, so we'll improve it in this sense ;)

**Comment by tiloyi** [comment]
> Hello @tiloyi ,
> 
> Yes it's possible but it's required to use `<input>` and in exemple there is no `<label>`.
> An exemple with valid code is better.

@yannkozon you're right, the documentation may not be explicit enough, so we'll improve it in this sense ;)
