### ISSUE TITLE
Focus can be out of modal

### ISSUE THREAD

**Issue by yannkozon** [adeo/mozaic-design-system#711]
# 🐞 Pattern bug report

### Where did you experience this bug ?
	
- [ ] On sketch file
- [x] On Documentation
- [x] On source code

### Description

When modal is open, the focus state can be out of this modal.
For accessibility reasons, the focus must be into modal context and it can be close with esc key.

## 🔬 Steps to reproduce the issue
In page with modal, add link and use keyboard navigation.

**Comment by mohamedMok** [comment]
Hi @yannkozon, 
Thanks for your issue, 
As you might know, our design system handles only `html/css` and documentation but no JS. 
I added a few rules to make it will be correctly implemented

The focus and event management will be done in our JS implementation. 
We have currently a PR on Mozaic-Vue if you want to check it out. 
https://github.com/adeo/mozaic-vue/pull/138
