### ISSUE TITLE
fix(hero): level down the z-index

### ISSUE THREAD

**Issue by Marine-Fabien** [adeo/mozaic-design-system#717]
# 🐞 Styleguide bug report

### Is this a regression?

No

### Description

We have a bug in LM website with the new "hero" component . In fact, the `z-index` level of `mc-hero__boxed` class  is too high for our navigation layer. If you don't mind, could you, please, level down it ? 
Our header layer => `z-index: 10` so if you could move yours below 10, it will be perfect!

## 🔥 Exception or Error
<pre>.mc-hero__boxed {
    flex: 100%;
    position: relative;
    margin-top: -6rem;
    z-index: 10;
}<code>
</code></pre>

## 📷  capture
![image (6)](https://user-images.githubusercontent.com/77010633/104037329-df86c480-51d4-11eb-8250-010decf5dd8b.png)

## 🌍 Your Environment
chrome

**Comment by mohamedMok** [comment]
Fixed by https://github.com/adeo/mozaic-design-system/commit/e596db1160f4ba110c9aa7071d16f038ce774bef

**Comment by mohamedMok** [comment]
Thanks to @tiloyi 💯
