### ISSUE TITLE
Input type number KO

### ISSUE THREAD

**Issue by alaxandre-duhayon** [adeo/mozaic-design-system#740]
In Mozilla Firefox, on select type number we have the Mozilla arrow style : 
![image](https://user-images.githubusercontent.com/52421478/108520360-e07a3e00-72ca-11eb-9aa7-b26c4959c6bf.png)

**Comment by mohamedMok** [comment]
Hello @alaxandre-duhayon,

Thanks for your feedback, I will provide a fix for this behavior on Mozilla.
