### ISSUE TITLE
Phone number field

### ISSUE THREAD

**Issue by mohamedMok** [adeo/mozaic-design-system#748]
# 🚀 Pattern addition proposal

### Description
Create a phone number field.
Pattern asked by @fgruchala

**Anything else relevant?**
![giphy](https://user-images.githubusercontent.com/7878860/109530573-26978480-7ab7-11eb-84ac-202e694cfc27.gif)

**Comment by fgruchala** [comment]
Thx for the assignement, I would to dispatch to my PO but it doesn't to be in this repo, right ? @JohanVMi
