### ISSUE TITLE
Accordion's transition bug

### ISSUE THREAD

**Issue by matthieu-castier** [adeo/mozaic-design-system#755]
# 🐞 Styleguide bug report

### Is this a regression?

 No

### Description

 
On accordions, when you open an element, there is a transition that takes place on the content. But the transition is only done on the padding. `transition: max-height 0.3s ease-out, padding 0.3s linear;`

So when you open it, all the text is displayed and there is a transition on the padding.

## 🔬 Steps to reproduce the issue

All you have to do is create an accordion with a lot of content and test the opening of an element.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment

**Styleguide Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by tiloyi** [comment]
Hello @matthieu-castier ,
Thank you for your issue and for bringing this to our attention.

We are currently working on reviewing all the interactions and animations on Mozaic. 
So, we will correct your issue when we will have defined these new rules of interactions.
