### ISSUE TITLE
autoprefixer no longer works

### ISSUE THREAD

**Issue by Marine-Fabien** [adeo/mozaic-design-system#805]
# 🐞 Styleguide bug report

### Is this a regression?
Yes

Yes, the previous version in which this bug was not present was: v1.6.0

### Description

 A clear and concise description of the problem...

## 🔬 Steps to reproduce the issue
When we use the PostCSS Mozaic configuration in the LM socle, browsers are not defined, and therefore we lose the autoprefixer.

## 🔥 Exception or Error
<pre><code>
Running production plugins
Processor {
  version: '7.0.35',
  plugins: [
    [Function (anonymous)] {
      postcssPlugin: 'postcss-prepend',
      postcssVersion: '7.0.35'
    },
    [Function (anonymous)] {
      postcssPlugin: 'postcss-sass',
      postcssVersion: '7.0.35'
    },
    [Function (anonymous)] {
      postcssPlugin: 'postcss-base64',
      postcssVersion: '5.2.18'
    },
    [Function (anonymous)] {
      postcssPlugin: 'postcss-media-queries-packer-on-demand',
      postcssVersion: '7.0.35'
    },
    [Function: plugin] {
      options: {},
      browsers: undefined,
      info: [Function (anonymous)],
      postcssPlugin: 'autoprefixer',
      postcssVersion: '7.0.35'
    },
    [Function (anonymous)] {
      postcssPlugin: 'cssnano',
      postcssVersion: '7.0.35'
    }
  ]
}
</code></pre>

## 🌍 Your Environment
https://github.com/adeo/integration-web-core--socle

**Comment by tiloyi** [comment]
Hello @Marine-Fabien ,
As seen together, it seems that the `.browserslistrc` file present in the socle is not read in the modules of features teams.

The Browserslist documentation indicates how the `.browserslistrc` file is called here => https://github.com/browserslist/browserslist#queries

So, for the problem you have, three solutions can be considered: 

- Tell each feature team to add a `.browserslistrc' file to the root of their module
- Or make a command in the socle that would change the package.json of the modules by adding the browserlist's rules
- Or you have to pass in the socle the Browserslist config as an environment variable in the following way: `process.env.BROWSERSLIST="last 2 versions, firefox >= 45, IE >= 11"`

I hope that these elements will help you.
I remain at your disposal if needed,
