### ISSUE TITLE
[Phone Number Input] Format and validate

### ISSUE THREAD

**Issue by fgruchala** [adeo/mozaic-design-system#819]
# 🚀 Pattern enhancement proposal

### What kind of enhancement are you proposing ?
	
- [ ] On sketch file
- [ ] On Documentation
- [x] On source code

### Description

On the [Phone Number input](https://mozaic.adeo.cloud/Components/Form/PhoneNumberInput/), is it possible to have : 
- a formatting helper based on the locale ?
- a validation helper based on the locale ?
- a customization of the available country ? e.g. by default, all countries but if we have to, just ask for France and Italian. **Not required, depends on your time**
- a customization of the default country ? e.g. I'm in leroymerlin.fr, by default, it's France

Here is a Javascript library based on a Google Android library : https://www.npmjs.com/package/libphonenumber-js
You can play with it here : https://catamphetamine.gitlab.io/libphonenumber-js/

### Justification

To be HMBU compliant on a middle and long term.
Propose a comfort way to our customer to fill their phone number.

**Comment by fgruchala** [comment]
Follow our call, @mohamedMok @tiloyi, you can imagine take these points : 
- a formatting helper based on the locale ?
- a customization of the default country ? e.g. I'm in leroymerlin.fr, by default, it's France

**Comment by mohamedMok** [comment]
https://github.com/adeo/mozaic-vue/pull/243

**Comment by mohamedMok** [comment]
@fgruchala @ysellamiLM 
I close this issue as the fix has been released. 

Feel free to re-open if needed
