### ISSUE TITLE
docs(onboard): add how to import mozaic icons in JS frameworks

### ISSUE THREAD

**Issue by mohamedMok** [adeo/mozaic-design-system#827]
The Mozaic documentation doesn't give a clear explanation on how to import icons in a project and how to use them. 

Mozaic must give a clear way of importing icons and all static assets in a project by frameworks. 
In this section, Mozaic should explain what is their motivation behind their choices. For example what framework are supported and why?  

Example: 
How to add Mozaic icons using Angular :
- Add to the build object the following code. It will copy all `svgs` in your `assets/images` directory
```js 
{
                "glob": "**/*",
                "input": "./node_modules/@mozaic-ds/icons/svg/",
                "output": "./assets/images"
              }
```

**Comment by tiloyi** [comment]
Resolves by https://github.com/adeo/mozaic-design-system/pull/1217
