### ISSUE TITLE
Possibility to display a Toggle without label

### ISSUE THREAD

**Issue by humbkr** [adeo/mozaic-design-system#860]
# 🚀 Styleguide feature request

### Description
Currently the Toggle styling is using a `:before` pseudo-class on the label, so you have to include a label in order to display a toggle.
If you omit the label, the toggle is not displayed at all.

Works:
```
<div class="mc-toggle">
  <input class="mc-toggle__input" id="example" type="checkbox" />
  <label class="mc-toggle__label" for="example">Label</label>
</div>
```

Does not work:
```
<div class="mc-toggle">
  <input class="mc-toggle__input" id="example" type="checkbox" />
</div>
```

This is problematic when you want to use a toggle at the end of a line like this:
<img width="1063" alt="Screenshot 2021-06-25 at 11 48 38" src="https://user-images.githubusercontent.com/845297/123407730-8f49c600-d5ac-11eb-8650-f3769ad00c28.png">

Another example would be an iOS settings-like screen.

### Describe the solution you'd like
It would be more interesting to allow users to use a Toggle without a label as it would cover more use-cases

### Describe alternatives you've considered
We can put an empty label but it will still display a space right after the toggle, which is annoying to position the elements on a page precisely without weird hacks.

**Comment by tiloyi** [comment]
Hi @humbkr ,
I just made a PR that adds a variation to get the result you want.

=> https://github.com/adeo/mozaic-design-system/pull/867

I'll let you have a look at it and comment on the PR if you like it, or you want us to make further changes.
