### ISSUE TITLE
Button `primary`+`bordered` doesn't respect declination/theme pattern

### ISSUE THREAD

**Issue by pinguet62** [adeo/mozaic-design-system#862]
# 🐞 Pattern bug report

### Where did you experience this bug ?
	
- [ ] On sketch file
- [ ] On Documentation
- [x] On source code

### Is this a regression?

 No

### Description

`theme` a `declination` seem respect a pattern like `mc-button--${declination}-${theme}`
👍 Perfect because this help usage (with string template)

But `mc-button--bordered-primary` doesn't work

## 🔬 Steps to reproduce the issue

`<button class="mc-button mc-button--bordered-primary">`

## 📷 Screenshot (optional - it might be a gif) or Sketch file (if existing)

![image](https://user-images.githubusercontent.com/2929786/123617281-5eb19880-d807-11eb-9221-532433e66b78.png)

## 🔥 Exception or Error

No error.

## 🌍 Your Environment

* website: `v1.12.0`
* `@mozaic-ds/styles`: 1.10.0

**Anything else relevant?**

After investigation, in `@mozaic-ds/tokens/build/scss/_tokens.scss`  entries `color.button.bordered-primary.*` are missing.

**Comment by tiloyi** [comment]
Hello @pinguet62 ,
Thanks for your message, but it is not a bug if the `--solid-primary` and `--bordered-primary` modifiers do not exist and are not implemented in Mozaic.

The primary color is the default color that is applied to the buttons. 
Therefore, it does not need to be set through a class or a modifier.

**Comment by pinguet62** [comment]
In computer science, I always seen "optional parameter" behavior like "with or without value the result is the same".
JavaScript example: 
```javascript
function doSomething(param = 'toto') { /*...*/ }

doSomething() === doSomething('toto')
```

In fact the real problem is the **usage**:
all users have to exclude the default behavior from the global pattern.
TypeScript example:
```typescript
function getVariation(
        theme: 'primary'| 'primary-02'| 'neutral'| 'danger',
        declination: 'solid' | 'bordered') {
    if (theme === 'primary') {
        if (declination === 'solid') {
            return ''
        } else {
            return 'mc-button--solid'
        }
    } else {
        return `mc-button--${declination}-${theme}`
    }
}
// VS
function getVariation(
        theme: 'primary'| 'primary-02'| 'neutral'| 'danger',
        declination: 'solid' | 'bordered') {
    return `mc-button--${declination}-${theme}`
}
```

> it is not a bug
> it does not need to be set through a class or a modifier.

Depending on your point of view 😉

If it's not a bug, so it's a **conception** problem.
There are 2 independ notions (2D matrix theme/declination), but some intersections are not allowed, hen there is no reason.

Do you prefer I create an other type of issue? (Styleguide feature request, Pattern ...)

**Comment by pinguet62** [comment]
I found a solution in my side tu use `mc-button--${declination}-${theme}` (instead of many-`if`) : 
```scss
.mc-button--bordered-primary {
  @extend .mc-button--bordered
}
```

Acceptable to me: **problem solved**!

👍 if you judge interesting to add this workaround (or directly `mc-button--bordered-primary` 😉) to your solution.
