### ISSUE TITLE
Missing positioning options in ml-flexy layout

### ISSUE THREAD

**Issue by humbkr** [adeo/mozaic-design-system#908]
# 🚀 Pattern enhancement proposal

### What kind of enhancement are you proposing ?
	
- [ ] On sketch file
- [ ] On Documentation
- [x] On source code

### Description

The ml-flexy layout classes are missing a lot of positioning options. For example I can add the
```
ml-flexy--justify-center
ml-flexy--justify-between
```
classes, but if I want to align my items at the end of the flexbox there isn't any class available.

### Justification
I would like not to have to write custom styles to be able to use the Mozaic layout system, it kinda defeat the purpose of using a framework in the first place.

**Comment by mohamedMok** [comment]
Hello @humbkr, 
Thanks for your feedback. 

I will add the following modifier, let me know if you think of any others.

**Comment by mohamedMok** [comment]
`ml-flexy--justify-evenly`
`ml-flexy--justify-end`
`ml-flexy--justify-start`
`ml-flexy--items-start`
