### ISSUE TITLE
Text input inside Layer

### ISSUE THREAD

**Issue by pinguet62** [adeo/mozaic-design-system#978]
# 🐞 Styleguide bug report

### Is this a regression?

I don't know: since `1.19.0`.

### Description

When a *Text Input* is in a *Layer*, the "focus effect" is hidden on left & right.

## 🔬 Steps to reproduce the issue

1. Copy sample https://mozaic.adeo.cloud/Components/Layers/code/#usage
2. Replace `<!-- Here your content -->` by sample https://mozaic.adeo.cloud/Components/Form/TextInput/code/#usage

## 📷 Screenshot (optional - it might be a gif)

![image](https://user-images.githubusercontent.com/2929786/145403833-fe7a8633-d0e3-4934-b82c-cbd542ae219f.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment

**Styleguide Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by tiloyi** [comment]
Hi @pinguet62 ,
Indeed this problem has been reported to us, and we are thinking about an evolution of the component that would not produce this problem.

However, if you wish, you can use the "edge" variation of the component, which allows you to shift the scrollbar and thus not have the problem you are experiencing.

More information via this link: https://mozaic.adeo.cloud/Components/Layers/code/#scrollbar-on-layer
