### ISSUE TITLE
chore(css-dev-tools): enable token export based on parameter

### ISSUE THREAD

**Issue by mohamedMok** [adeo/mozaic-design-system#996]
Each time `npx mozaic-tokens-build` all the tokens are generated. 

The problem is that most of the time end users will only need the token file according to their project environment. And they end up with token files for all libraries Mozaic serves (swift, XML,...) 

The proposed solution is to enable a parameter for the user to choose the format of the token to generate. 

`npx mozaic-tokens-build scss js`

**Comment by tiloyi** [comment]
Fixed by: https://github.com/adeo/mozaic-design-system/pull/1189
